"""Zcord - Minimalistic discord API wrapper."""

from importlib.metadata import version

from ._logging import setup_logging
from .bot import Bot
from .missing import MISSING
from .models import (
    ActionRow,
    Application,
    ApplicationCommandInteractionData,
    Attachment,
    AvatarDecorationData,
    Button,
    Channel,
    Collectibles,
    Component,
    ComponentInteractionData,
    DefaultReaction,
    DefaultValue,
    Embed,
    EmbedAuthor,
    EmbedField,
    EmbedFooter,
    EmbedImage,
    EmbedProvider,
    EmbedVideo,
    Emoji,
    Guild,
    InstallParams,
    Interaction,
    InteractionData,
    InteractionMetadata,
    InteractionResponse,
    Member,
    Message,
    ModalSubmitInteractionData,
    Model,
    Nameplate,
    Poll,
    PollAnswer,
    PollAnswerCount,
    PollMedia,
    PollResults,
    PrimaryGuild,
    Reaction,
    ReactionCountDetails,
    Role,
    RoleColors,
    RoleSubscriptionData,
    RoleTags,
    SelectMenu,
    SelectOption,
    SharedClientTheme,
    Snowflake,
    Sticker,
    StringSelect,
    Team,
    TeamMember,
    ThreadMember,
    ThreadMetadata,
    User,
    UserSelect,
)

__version__ = version("zcord")
"""
Zcord version
"""

__all__ = [
    "MISSING",
    "ActionRow",
    "Application",
    "ApplicationCommandInteractionData",
    "Attachment",
    "AvatarDecorationData",
    "Bot",
    "Button",
    "Channel",
    "Collectibles",
    "Component",
    "ComponentInteractionData",
    "DefaultReaction",
    "DefaultValue",
    "Embed",
    "EmbedAuthor",
    "EmbedField",
    "EmbedFooter",
    "EmbedImage",
    "EmbedProvider",
    "EmbedVideo",
    "Emoji",
    "Guild",
    "InstallParams",
    "Interaction",
    "InteractionData",
    "InteractionMetadata",
    "InteractionResponse",
    "Member",
    "Message",
    "ModalSubmitInteractionData",
    "Model",
    "Nameplate",
    "Poll",
    "PollAnswer",
    "PollAnswerCount",
    "PollMedia",
    "PollResults",
    "PrimaryGuild",
    "Reaction",
    "ReactionCountDetails",
    "Role",
    "RoleColors",
    "RoleSubscriptionData",
    "RoleTags",
    "SelectMenu",
    "SelectOption",
    "SharedClientTheme",
    "Snowflake",
    "Sticker",
    "StringSelect",
    "Team",
    "TeamMember",
    "ThreadMember",
    "ThreadMetadata",
    "User",
    "UserSelect",
    "setup_logging",
]
