name: PyPI Publish

on:
  push:
    tags:
      # Match mixed CalVer pattern:
      # - YEAR.FEAT.PATCH[(.TAG)(REVISION)]
      # - 2026.1.2a1
      # - 2026.3.4b2
      # - 2026.5.6rc3
      # - 2026.7.8
      - "[0-9]{4}.[0-9]+.[0-9]+(?:a[0-9]+|b[0-9]+|rc[0-9]+)?"

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/zcord
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup uv and python
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
        with:
          python-version: "3.12"

      - name: Build package
        run: uv build

      - name: Validate package
        run: |
          uvx twine check dist/*
          uv run --isolated --no-project --with dist/*.whl python -c "import zcord; print(zcord.__version__)"

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # release/v1
        with:
          packages-dir: dist/

        # Get the content between the first 2 separators (---)
      - name: Extract release notes
        run: |
          awk '/^[[:space:]]*---[[:space:]]*$/{n++; next} n==1' docs/CHANGELOG.md > "$RUNNER_TEMP/notes.md"
          [ -s "$RUNNER_TEMP/notes.md"] || { echo "No release notes"; exit 1; }

      - name: Create release
        run: gh release create "${{ github.ref_name }}" --notes-file "$RUNNER_TEMP/notes.md" dist/*.tar.gz dist/*.whl # Idk what the attestation files do but they're probably not needed for release
        env:
          GH_TOKEN: ${{ github.token }}
