name: PyPI Publish

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"  # 2026.1.0
      - "[0-9]+.[0-9]+.[0-9]+.*"  # 2026.1.0.alpha1

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/zcord
    steps:
      - uses: actions/checkout@v7

      - name: Setup uv and python
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          python-version: "3.12"

      - name: Build package
        run: uv build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/

        # Get the content between the first 2 separators (---)
      - name: Extract release notes
        run: |
          awk '/^[[:space:]]*---[[:space:]]*$/{n++; next} n==1' docs/CHANGELOG.md > "$RUNNER_TEMP/notes.md"
          [ -s "$RUNNER_TEMP/notes.md"] || { echo "No release notes"; exit 1; }

      - name: Create release
        run: gh release create "${{ github.ref_name }}" --notes-file "$RUNNER_TEMP/notes.md" dist/*.tar.gz dist/*.whl  # Idk what the attestation files do but they're probably not needed for release
        env:
          GH_TOKEN: ${{ github.token }}
